spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:flight_management_database
    username: test
    password: test

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        connection:
          autocommit: false
    hibernate:
      ddl-auto: none

  h2.console.enabled: true

crazy-supplier:
  url: http://localhost:8091
  default:
    connectTimeout: 2000
    readTimeout: 3000

resilience4j:
  circuitbreaker:
    instances:
      crazy-supplier-service:
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3


logging:
  level.root: INFO