DROP TABLE FLIGHT IF EXISTS;

CREATE TABLE FLIGHT(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    AIRLINE VARCHAR(255) NOT NULL,
    SUPPLIER VARCHAR(255) NOT NULL,
    FARE DECIMAL(19, 2) NOT NULL,
    DEPARTURE_AIRPORT VARCHAR(3) NOT NULL,
    DESTINATION_AIRPORT VARCHAR(3) NOT NULL,
    DEPARTURE_TIME TIMESTAMP NOT NULL,
    ARRIVAL_TIME TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_BY VARCHAR(255) NOT NULL,
    LAST_UPDATED_AT TIMESTAMP NOT NULL
);

CREATE INDEX idx_airline ON FLIGHT(AIRLINE);
CREATE INDEX idx_departure_airport ON FLIGHT(DEPARTURE_AIRPORT);
CREATE INDEX idx_destination_airport ON FLIGHT(DESTINATION_AIRPORT);
CREATE INDEX idx_departure_time ON FLIGHT(DEPARTURE_TIME);
CREATE INDEX idx_arrival_time ON FLIGHT(ARRIVAL_TIME);